name: SWERI Processing Staging
services:
  app:
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: /data-processing/staging
        awslogs-create-group: "true"
        awslogs-stream: app

  rabbit:
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: /data-processing/staging
        awslogs-create-group: "true"
        awslogs-stream: rabbit

  celery:
     logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: /data-processing/staging
        awslogs-create-group: "true"
        awslogs-stream: celery

  redis:
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: /data-processing/staging
        awslogs-create-group: "true"
        awslogs-stream: redis

  db:
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: /data-processing/staging
        awslogs-create-group: "true"
        awslogs-stream: db
