name: dailyprogression
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - "../.env"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"  
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${HOST_PGADMIN_DATA_PATH}:/var/lib/pgadmin
  db:
    image: postgis/postgis:15-3.5
    env_file:
      - "../.env"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    shm_size: 1gb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c max_wal_size=5GB -c wal_level=minimal -c synchronous_commit=off -c max_wal_senders=0
  app:
    image: ${DOCKER_IMAGE_NAME}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - "../.env"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    depends_on:
      db:
        condition: service_healthy
    command: python daily_progression.py
    volumes:
      - ..:/src


volumes:
  postgres_data:
