name: Update ECR Image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: sweri-data-tools

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    name: Update latest ECR image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ECR_IAM_ARN}}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

#      - name: Set image tag to branch name
#        if:  github.ref != 'refs/heads/main'
#        run: |
#          echo "ECR_TAG=${{github.ref}}" >> "$GITHUB_ENV"
#
#      - name: Set image tag to latest
#        if:  github.ref == 'refs/heads/main'
#        run: |
#          echo "ECR_TAG=latest" >> "$GITHUB_ENV"

      - name: Get tags for backend image
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
          tags: |
            type=raw,value=${{ inputs.tag}}
            type=sha

      - name: Build and tag image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          file: ./docker/Dockerfile
          context: .
          load: true
          tags: ${{ inputs.tag }}
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Push backend image to Amazon ECR
        id: push-image
        uses: docker/build-push-action@v6
        with:
          file: ./docker/Dockerfile
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tag }}
