name: Unit test python library

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: sweri-data-tools

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
jobs:
  unit_test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    environment: production
    name: unit test python lib
    steps:
#      - name: Install libkrb5 for Kerberos on Linux
#        run: |
#          sudo apt-get update
#          sudo apt-get install libkrb5-dev
#          pip install requests-kerberos
      - name: checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ECR_IAM_ARN}}
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'
#      - uses: actions/setup-python@v5
#        with:
#          python-version: 3.11.8
#      - name: install deps
#        run: pip install -r requirements.testing.txt
#      - name: run tests
#        run: pytest --cov=sweri_utils ./sweri_utils/tests.py
      - name: Build and tag backend image
        id: build-image-backend
        uses: docker/build-push-action@v6
        with:
          file: ./docker/Dockerfile
          context: .
          load: true
          cache-from: type=registry,ref=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
      - name: Run backend unit tests
        run: |
          docker run ${{ steps.build-image-backend.outputs.imageid }} \
            sh -c "pytest --cov=sweri_utils ./sweri_utils/tests.py && coverage report --format=markdown" >> $GITHUB_STEP_SUMMARY
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
